create table category
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint uk46ccwnsi9409t36lurvtyljak
            unique
);

create table format
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint ukga3lshnphl8w3jw8yflq7w9rs
            unique
);

create table category_format
(
    format_id   bigint not null
        constraint fkq1ta1l5yu1soq61elss5jxnu8
            references format,
    category_id bigint not null
        constraint fk2ru59u5l2f930rq4pe28ec5tf
            references category,
    primary key (format_id, category_id)
);

create table language
(
    id   bigint generated by default as identity
        primary key,
    code varchar(255),
    name varchar(255) not null
);

create table notification
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6)  not null,
    message         varchar(1000) not null,
    is_read         boolean       not null,
    related_chapter bigint,
    related_user    bigint,
    related_work    bigint,
    type            varchar(50)   not null
        constraint notification_type_check
            check ((type)::text = ANY
                   ((ARRAY ['WORK_UPDATED'::character varying, 'NEW_WORK_PUBLISHED'::character varying, 'NEW_WORK_SUBSCRIBER'::character varying, 'NEW_AUTHOR_SUBSCRIBER'::character varying, 'NEW_CHAPTER_SUBSCRIBER'::character varying])::text[])),
    user_id         bigint        not null
);

create table payment_processed
(
    payment_id varchar(64) not null
        primary key
);

create table payment_record
(
    id                 varchar(64)    not null
        primary key,
    amount             numeric(38, 2) not null,
    created_at         timestamp(6) with time zone,
    currency           varchar(8),
    external_reference varchar(128),
    payment_method     varchar(64),
    provider           varchar(255)   not null,
    session_uuid       varchar(64),
    status             varchar(32),
    subscription_type  varchar(16),
    target_id          bigint,
    title              varchar(255)   not null,
    user_id            bigint         not null
);

create table payment_session_link
(
    external_reference varchar(128) not null
        primary key,
    created_at         timestamp(6) with time zone,
    session_uuid       varchar(64)
);

create table ratings
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6)     not null,
    rating     double precision not null,
    user_id    bigint           not null,
    work_id    bigint           not null
);

create table registration_token
(
    id            bigint generated by default as identity
        primary key,
    code          varchar(255) not null,
    email         varchar(255) not null
        constraint ukodecv1use2h4kd7puvfvrujk5
            unique,
    expires_at    timestamp(6) not null,
    name          varchar(255) not null,
    password_hash varchar(255) not null,
    surname       varchar(255) not null,
    username      varchar(255) not null
);

create table suscribe_chapter
(
    chapter_id bigint       not null,
    user_id    bigint       not null,
    work_id    bigint       not null,
    created_at timestamp(6) not null,
    notified   boolean      not null,
    primary key (chapter_id, user_id, work_id)
);

create table tag
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

create table "user"
(
    id                      bigint generated by default as identity
        primary key,
    email                   varchar(255)          not null
        constraint ukhl4ga9r00rh51mdaf20hmnslt
            unique,
    enabled                 boolean default false not null,
    money                   numeric(38, 2)        not null,
    name                    varchar(255)          not null,
    password                varchar(255)          not null,
    photo                   varchar(255),
    surname                 varchar(255)          not null,
    username                varchar(255)          not null
        constraint uk5c856itaihtmi69ni04cmpc4m
            unique,
    verification_code       varchar(255),
    verification_expires_at timestamp(6),
    price                   numeric(38, 2)
);

create table preferred_category
(
    user_id     bigint not null
        constraint fk585ui0urqqo33043ldn9i12kr
            references "user",
    category_id bigint not null
        constraint fk6xhwmubhy6mtakamtwh69rlox
            references category,
    primary key (user_id, category_id)
);

create table preferred_language
(
    user_id     bigint not null
        constraint fk6ce5iqdlggont3e1qqkpb6a3e
            references "user",
    language_id bigint not null
        constraint fk2ddp8397nuiyd349akr8tsqoa
            references language,
    primary key (user_id, language_id)
);

create table suscribe_autor
(
    autor_id   bigint       not null
        constraint fk95bncw88809yfe17gfiuhklla
            references "user",
    user_id    bigint       not null
        constraint fkcwad2v3ppm2fxj8w15xo8fobw
            references "user",
    created_at timestamp(6) not null,
    notified   boolean      not null,
    primary key (autor_id, user_id)
);

create table user_reading_history
(
    id         bigint generated by default as identity
        primary key,
    chapter_id bigint not null,
    read_at    timestamp(6),
    user_id    bigint not null,
    work_id    bigint not null
);

create table work
(
    id                   bigint generated by default as identity
        primary key,
    average_rating       double precision,
    banner               varchar(2048),
    cover                varchar(2048),
    description          text           not null,
    has_epub             boolean        not null,
    has_pdf              boolean        not null,
    lenght_epub          integer,
    length_pdf           integer,
    likes                integer        not null,
    price                numeric(10, 2) not null,
    publication_date     date,
    rating_count         integer,
    state                varchar(255)   not null,
    title                varchar(2048)  not null,
    creator_id           bigint         not null
        constraint fk1aasl3rtp1fe6ynwxw5kpb64m
            references "user",
    format_id            bigint         not null
        constraint fkdxb48pxte4tmwybv0g1s6tigp
            references format,
    original_language_id bigint         not null
        constraint fkbq5r7sqfum4yr62961d3amls3
            references language
);

create table chapter
(
    id                         bigint generated by default as identity
        primary key,
    allow_ai_translation       boolean not null,
    last_update                timestamp(6),
    likes                      bigint  not null,
    price                      numeric(10, 2),
    publication_status         varchar(255),
    published_at               timestamp(6),
    scheduled_publication_date timestamp(6),
    title                      varchar(255),
    language_id                bigint
        constraint fk7rufgat0j5yabm4e1nm3gyuue
            references language,
    work_id                    bigint  not null
        constraint fkdj6je5qtp0a0jqwap9v5fa71
            references work
);

create table chapter_likes
(
    id         bigint generated by default as identity
        primary key,
    liked_at   timestamp(6),
    chapter_id bigint not null
        constraint fk15f7ayrsr0ltfn3b212lr1eb3
            references chapter,
    user_id    bigint not null
        constraint fkkm413s1c9rdcprregw3g51pu5
            references "user",
    constraint ukrygypiqde2puskboecyrhg7pd
        unique (user_id, chapter_id)
);

create table likes_work
(
    id       bigint generated by default as identity
        primary key,
    liked_at timestamp(6),
    user_id  bigint not null
        constraint fkf3hqj09qngd5vky4i8fep1c28
            references "user",
    work_id  bigint not null
        constraint fko61u55t751kty6t2s7b2b0s7e
            references work,
    constraint ukrl6pkx5qym1eoo9ppql7l0wsl
        unique (user_id, work_id)
);

create table suscribe_work
(
    user_id    bigint       not null
        constraint fkixkogkh5nen2494o5eumrly9q
            references "user",
    work_id    bigint       not null
        constraint fk3fgcmsu2h3nwgrqkla6wht9w7
            references work,
    created_at timestamp(6) not null,
    notified   boolean      not null,
    primary key (user_id, work_id)
);

create table user_chapter
(
    user_id    bigint not null
        constraint fkmdo82bgguhwhcyfmwths2oa9d
            references "user",
    chapter_id bigint not null
        constraint fk90rlio5k11i6wikro6jqq75g7
            references chapter,
    primary key (user_id, chapter_id)
);

create table user_reading_progress
(
    user_id    bigint not null
        constraint fkawlg38myw5lu3ptccbfaoomkl
            references "user",
    chapter_id bigint,
    work_id    bigint not null
        constraint fkfux501rx8m0sv00f5gptgddak
            references work,
    primary key (user_id, work_id)
);

create table version
(
    id          bigint generated by default as identity
        primary key,
    content     oid,
    chapter_id  bigint not null
        constraint fks6ujqsr0ah03s576wprvgg90w
            references chapter,
    language_id bigint not null
        constraint fkk2iu64xgvhf9eulyui5v7mxr1
            references language
);

create table work_category
(
    work_id     bigint not null
        constraint fkd42oway4aoyt3rg761lhhq81p
            references work,
    category_id bigint not null
        constraint fkaurjlyxxrbww1hiioq3jl3enb
            references category,
    primary key (work_id, category_id)
);

create table work_saved
(
    id       bigint generated by default as identity
        primary key,
    saved_at timestamp(6),
    user_id  bigint not null
        constraint fk5qpkvq935pgj9ecepmca6kg1w
            references "user",
    work_id  bigint not null
        constraint fkr6qr6uld1dfy7r2dj2wv8jh4y
            references work
);

create table work_tag
(
    work_id bigint not null
        constraint fkliybd2bkgphrdsa0wosy5mguh
            references work,
    tag_id  bigint not null
        constraint fkqrhno4bemgng5i4p36cojki5x
            references tag,
    primary key (work_id, tag_id)
);

